FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o checkout-service ./main.go

FROM alpine:3.20

WORKDIR /app

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /app/checkout-service .
COPY --from=builder /app/config ./config
COPY --from=builder /app/migration ./migration
COPY --from=builder /app/config/application_docker.json ./application_docker.json

EXPOSE 4000
EXPOSE 9090

CMD ["./checkout-service", "-env", "docker"]